# Generated by Django 4.2.3 on 2023-08-31 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0042_alter_analyticview_created_by_and_more'),
    ]

    operations = [
    ]
